In [3]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.2-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 3.8 MB/s eta 0:00:03
   ----- ---------------------------------- 1.3/9.8 MB 3.8 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.8 MB 3.7 MB/s eta 0:00:03
   ---------- ----------------------------- 2.6/9.8 MB 3.5 MB/s eta 0:00:03
   ------------- -------------------------- 3.4/9.8 MB 3.6 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.8 MB 3.6 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/9.8 MB 3.7 MB/s eta 0:00:02
   ------------------------ --------------- 6.0/9.8 MB 3.7 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.8 MB 3.8 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.8 MB 3.9 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.8 MB 3.9 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 3.6 MB/s  0:00:02
Downloading numpy-2.5.2-cp313-cp313-win_amd64.whl (12.5 MB)
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.5 MB 4.1 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/12.5 MB 4.1 MB/s eta 0:00:03
   ------- -------------------------------- 2.4/12.5 MB 4.2 MB/s eta 0:00:03
   ---------- ----------------------------- 3.1/12.5 MB 3.8 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.5 MB 3.8 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.5 MB 3.5 MB/s eta 0:00:03
   --------------- ------------------------ 5.0/12.5 MB 3.5 MB/s eta 0:00:03
   ------------------ --------------------- 5.8/12.5 MB 3.5 MB/s eta 0:00:02
   --------------------- ------------------ 6.6/12.5 MB 3.5 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.5 MB 3.6 MB/s eta 0:00:02
   -------------------------- ------------- 8.1/12.5 MB 3.6 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.5 MB 3.5 MB/s eta 0:00:02
   ------------------------------ --------- 9.4/12.5 MB 3.6 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.5 MB 3.6 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.5 MB 3.6 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.5 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 3.5 MB/s  0:00:03
Installing collected packages: numpy, pandas

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed numpy-2.5.2 pandas-3.0.5
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\Admin\AppData\Local\Programs\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: C:\Users\Admin\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [7]:
file_path = r"C:\Users\Admin\Desktop\Grocery Store Analytics\Data Set\Raw data\grocery_sales.csv"

# Load and view the data
sales = pd.read_csv(file_path)
sales.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Store_ID,Quantity,Unit_Price,Unit_Cost,Discount_Percent,Gross_Sales,...,Profit,Payment_Method,Product_Name,Category,Customer_Name,City,Age_Group,Member_Type,Store_Name,Store_Type
0,ORD00001,2024-11-06,C0240,P035,S004,1,300,150,5,300,...,135.0,Credit Card,Bucket,Cleaning & Household,Arjun Joshi,Hyderabad,55+,Regular,FreshMart Hyderabad,Supermarket
1,ORD00002,2024-05-07,C0082,P041,S001,2,30,20,5,60,...,17.0,Credit Card,Salt 1kg,Groceries & Food,Karan Kumar,Delhi,45-54,Regular,FreshMart Delhi Central,Supermarket
2,ORD00003,2026-09-06,C0044,P096,S003,2,500,260,0,1000,...,480.0,UPI,Desk Organizer,Home & Living,Rohan Mehta,Bengaluru,35-44,Regular,FreshMart Bengaluru Hub,Hypermarket
3,ORD00004,2025-12-02,C0066,P096,S007,2,500,260,15,1000,...,330.0,Debit Card,Desk Organizer,Home & Living,Vivaan Verma,Kolkata,35-44,Regular,FreshMart Kolkata,Supermarket
4,ORD00005,2025-06-25,C0365,P067,S006,2,450,280,0,900,...,340.0,UPI,Moisturizer,Personal Care,Ananya Singh,Pune,55+,Gold,FreshMart Pune,Supermarket

In [8]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          3000 non-null   str
 1   Order_Date        3000 non-null   str
 2   Customer_ID       3000 non-null   str
 3   Product_ID        3000 non-null   str
 4   Store_ID          3000 non-null   str
 5   Quantity          3000 non-null   int64
 6   Unit_Price        3000 non-null   int64
 7   Unit_Cost         3000 non-null   int64
 8   Discount_Percent  3000 non-null   int64
 9   Gross_Sales       3000 non-null   int64
 10  Discount_Amount   3000 non-null   float64
 11  Revenue           3000 non-null   float64
 12  Profit            3000 non-null   float64
 13  Payment_Method    3000 non-null   str
 14  Product_Name      3000 non-null   str
 15  Category          3000 non-null   str
 16  Customer_Name     3000 non-null   str
 17  City              3000 non-null   str
 18  Age_Group         3000 non-null   str
 19  Member_Type       3000 non-null   str
 20  Store_Name        3000 non-null   str
 21  Store_Type        3000 non-null   str
dtypes: float64(3), int64(5), str(14)
memory usage: 515.8 KB

In [10]:
sales.shape

(3000, 22)

In [12]:
#missing value
sales.isnull().sum()

Order_ID            0
Order_Date          0
Customer_ID         0
Product_ID          0
Store_ID            0
Quantity            0
Unit_Price          0
Unit_Cost           0
Discount_Percent    0
Gross_Sales         0
Discount_Amount     0
Revenue             0
Profit              0
Payment_Method      0
Product_Name        0
Category            0
Customer_Name       0
City                0
Age_Group           0
Member_Type         0
Store_Name          0
Store_Type          0
dtype: int64

In [14]:
#Duplicates value
sales.duplicated().sum()

np.int64(0)

In [15]:
#data types
sales["Order_Date"] = pd.to_datetime(
    sales["Order_Date"],
    errors="coerce"
)

In [16]:
#invalid Values
sales.describe()

,Order_Date,Quantity,Unit_Price,Unit_Cost,Discount_Percent,Gross_Sales,Discount_Amount,Revenue,Profit
count,3000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,2025-06-20 10:59:02.400000,1.908000,400.540000,237.314000,5.456667,761.136667,41.827083,719.309583,268.474917
min,2024-01-01 00:00:00,1.000000,30.000000,15.000000,0.000000,30.000000,0.000000,24.000000,4.000000
25%,2024-09-21 18:00:00,1.000000,140.000000,75.000000,0.000000,220.000000,0.000000,212.500000,80.000000
50%,2025-06-11 12:00:00,2.000000,280.000000,150.000000,5.000000,440.000000,7.500000,405.000000,155.500000
75%,2026-03-20 06:00:00,2.000000,450.000000,280.000000,10.000000,900.000000,45.000000,810.000000,320.000000
max,2026-12-31 00:00:00,5.000000,2500.000000,1700.000000,20.000000,12500.000000,1500.000000,11250.000000,3500.000000
std,NaN,1.050033,420.870826,270.591334,6.034920,1010.251055,94.490657,955.451799,330.578389

In [17]:
sales[
    (sales["Quantity"] <= 0) |
    (sales["Unit_Price"] <= 0) |
    (sales["Discount_Percent"] < 0) |
    (sales["Discount_Percent"] > 100)
]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_ID, Product_ID, Store_ID, Quantity, Unit_Price, Unit_Cost, Discount_Percent, Gross_Sales, Discount_Amount, Revenue, Profit, Payment_Method, Product_Name, Category, Customer_Name, City, Age_Group, Member_Type, Store_Name, Store_Type]
Index: []

[0 rows x 22 columns]

In [18]:
output_path = r"C:\Users\Admin\Desktop\Grocery Store Analytics\Data Set\Cleaned data\sales_cleaned.csv"

# Save the DataFrame to that path
sales.to_csv(output_path, index=False)